apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptowallet-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cryptowallet-server
      name: app-pod
  template:
    metadata:
      labels:
        app: cryptowallet-server
        name: app-pod
    spec:
      containers:
        - name: cryptowallet-server
          image: johnngugi/cryptowallet-server
          envFrom:
            - secretRef:
                name: app-secrets
            - secretRef:
                name: db-config
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 3000
