version: "3"
services:
    cryptowallet-server:
        build:
            context: .
        image: johnngugi/cryptowallet-server
        container_name: cryptowallet-server
        volumes:
            - ./application:/home/node/app/
            - /home/node/app/node_modules
        env_file: .env
        ports:
            - "3000:3000"
        networks:
            - app-network
        command: sh -c './wait-for -t 300 db:3306 -- npm run migrate && npm run dev'
        depends_on:
            - db
    db:
        image: mysql:8.0.18
        container_name: db
        env_file: .env
        environment:
            - MYSQL_USER=$DB_USER
            - MYSQL_PASSWORD=$DB_PASS
            - MYSQL_DATABASE=$DB_NAME
            - MYSQL_ROOT_PASSWORD=$DB_PASS
        ports:
            - "3308:3306"
        volumes:
            - "./tmp/mysql/data:/var/lib/mysql"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
